In [1]:
import numpy as np

a = np.arange(60).reshape(3, 4, 5)


In [2]:
print(a.shape)

(3, 4, 5)


In [3]:
a = a[1:,:,:]
print(a.shape)

(2, 4, 5)


In [8]:
a = np.vstack((a,np.zeros((1,)+a.shape[1:], dtype=a.dtype)))

In [5]:
print(a.shape)

(3, 4, 5)


In [9]:
print(a)

[[[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[10  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]

 [[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]]


In [6]:
list_lm=[]

x=1
y=2

list_lm.append(x)
list_lm.append(y)

In [9]:
print(max(list(map(abs, list_lm))))

2
