In [1]:
import numpy as np

a = np.arange(60).reshape(3, 4, 5)


In [2]:
print(a.shape)

(3, 4, 5)


In [3]:
a = a[1:,:,:]
print(a.shape)

(2, 4, 5)


In [4]:
a = np.vstack((a,np.zeros((1,)+a.shape[1:], dtype=a.dtype)))

In [5]:
print(a.shape)

(3, 4, 5)


In [23]:
print(a)

[[[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]
  [ 0  0  0  0  0]]]


In [22]:
print(a.shape)

(3, 4, 5)


In [50]:
c = a[0:1,:,:]

In [49]:
print(c.shape)

(0, 4, 5)


In [46]:
d = np.arange(60).reshape(3, 4, 5)

In [47]:
print(d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [44]:
d[0,:,:]=c[0,:,:]

In [45]:
print(d)

[[[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
