* Baseado no video: https://youtu.be/Dw2TdjgCJeo

In [1]:
import numpy as np

In [4]:
## Array 3D - obersar que o [] mais externo determina que e 3 D, e dentro tem um 2D.add()

array1=np.array([
    				[
            			[1,4,7],[3,5,2],[5,6,0]
               		],
        			[
						[7,4,1],[2,8,8],[0,3,6]
					]
           		])

In [7]:
array1.shape

(2, 3, 3)

In [8]:
print(array1)

[[[1 4 7]
  [3 5 2]
  [5 6 0]]

 [[7 4 1]
  [2 8 8]
  [0 3 6]]]


In [9]:
## Number of Dimensions 

array1.ndim

3

In [11]:
## Soma dos elementos 

array1.size

18

In [10]:
print(array1[1,0,0])

7


In [12]:
print(array1[1][0][0])

7


In [7]:
array1=array1[0,:,:]

In [10]:
print(array1)

[[1 4 7]
 [3 5 2]
 [5 6 0]]


In [4]:
buffer = np.zeros([10,3,3],dtype=np.uint16)
cx = np.zeros(3,dtype=np.uint16)

In [6]:
cx[0]=10
cx[1]=20
cx[2]=30

In [12]:
for i in range(0,10):
    for f in range(0,3):
        for g in range(0,3):
            buffer[i,f,g]=cx[g]

SyntaxError: expected ':' (1261177230.py, line 3)

In [11]:
print(buffer)

[[[10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]]]
